spring:
  profiles:
    active: local
  application:
    name: photosharex
  datasource:
    password: photosharex1234
    url: jdbc:postgresql://localhost:5432/photosharex
    username: photosharexuser
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_ADDRESS}
    password: ${GMAIL_PASS}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
gcp:
  cloud:
    bucket: photosharex
    bucket-directory: image/