name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ vars.Photosharex }}
    steps:
      - name: Print environment variables
        run: |
          echo "GOOGLE_APPLICATION_CREDENTIALS: ${{ vars.GOOGLE_APPLICATION_CREDENTIALS }}"
          echo "MAIL_ADDRESS: ${{ vars.MAIL_ADDRESS }}"
          echo "MAIL_PASS: ${{ vars.MAIL_PASS }}"
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ vars.GOOGLE_APPLICATION_CREDENTIALS }}
          MAIL_ADDRESS: ${{ vars.MAIL_ADDRESS }}
          MAIL_PASS: ${{ vars.MAIL_PASS }}

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" build
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ vars.GOOGLE_APPLICATION_CREDENTIALS }}
          MAIL_ADDRESS: ${{ vars.MAIL_ADDRESS }}
          MAIL_PASS: ${{ vars.MAIL_PASS }}

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ vars.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_PASSWORD }}/photosharex_api:latest
